version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: citybike
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
